spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/boardtest
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: always
logging:
  level:
    org.hibernate_type: trace